# Generated by Django 3.1 on 2020-08-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
